const SERVER_ENDPOINT = "http://10.0.0.1:7000";
const SERVER_ENDPOINT_RUN = `${SERVER_ENDPOINT}/run`;
const SERVER_ENDPOINT_TODAY = `${SERVER_ENDPOINT}/today`;

const SERVER_ENDPOINT_MAPPING = {
  agenda: SERVER_ENDPOINT + "/agenda",
  list: SERVER_ENDPOINT + "/list",
  add: SERVER_ENDPOINT + "/add",
  run: SERVER_ENDPOINT + "/run",
  today: SERVER_ENDPOINT + "/today"
};

export {
  SERVER_ENDPOINT_RUN,
  SERVER_ENDPOINT_TODAY,
  SERVER_ENDPOINT_MAPPING
};
