const SERVER_ENDPOINT = "http://10.0.0.3:7000";
const SERVER_ENDPOINT_RUN = `${SERVER_ENDPOINT}/run`;
const SERVER_ENDPOINT_TODAY = `${SERVER_ENDPOINT}/today`;

export {SERVER_ENDPOINT_RUN, SERVER_ENDPOINT_TODAY};
