name: Rust

on:
  push:
    branches: [ main , github-workflow]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy

    - name: Run tests
      run: cargo test --verbose
